provider: aws_cog
lat: 33.589
lon: 130.273
#buffer: 0.1
buffer_m: 10000
start: '2024-01-01'
end: '2024-02-28'
max_cloud: 30
min_valid: 30
satellite: 'Sentinel-2'
bands:
  - B02
  - B03
  - B04
  - B08
  - B11
  - SCL
  - dataMask


