bands:
  - data/raw/B02.tif
  - data/raw/B03.tif
  - data/raw/B04.tif
  - data/raw/B08.tif
  - data/raw/B11.tif
scl: data/raw/SCL.tif
mask: data/raw/MASK.tif
features_out: data/processed/features.npz
