# Training data directories containing the feature file listed below
input_dirs:
  - data/example_run/Sentinel-2/33.9160_130.7450_2024-01-01_2024-02-16
  # - path/to/another/download_folder
features: preprocess/features.npz
# Label raster inside each input directory
labels: labels.tif
model_out: outputs/model.pkl
n_estimators: 100
